trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/src/'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/src/'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

resources:
  repositories:
  - repository: templates
    type: github
    name: osisoft/OSI-Samples
    endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: projPath
    value: '/src/'
  - name: CredFile
    value: test_config.json
  - name: CredFileLibrary
    value: product-readiness.piweb_da.json
  - name: analysisProject
    value: PIWebAPI_Data_Analysis_Upload

jobs:
  - template: '/miscellaneous/build_templates/analysis.yml@templates'
    parameters:
      language: dotnet
